;variables in direct page

PROG          EQU $BE00
NUMARRAYS     EQU $BE02
NUMVARS       EQU $BE04
LABELS        EQU $BE06
STRINGS       EQU $BE08
LOOPS         EQU $BE0A
ELINE         EQU $BE0C
WRKSPC        EQU $BE0E
FREEMEM       EQU $BE10
INSERTPTR     EQU $BE12
RESERVE       EQU $BE14
PRTPOS_LINE   EQU $BE16
PRTPOS_COL    EQU $BE17
GMODE         EQU $BE18
INVERSE       EQU $BE19
GINVERSE      EQU $BE1A
OVER          EQU $BE1B
GOVER         EQU $BE1C
PAPER         EQU $BE1D
GPAPER        EQU $BE1E
INK           EQU $BE1F
GINK          EQU $BE20


TEMP0         EQU $BEF0 
TEMP1         EQU $BEF1
TEMP2         EQU $BEF2
TEMP3         EQU $BEF3
TEMP4         EQU $BEF4
TEMP5         EQU $BEF5
TEMP6         EQU $BEF6
TEMP7         EQU $BEF7
TEMP8         EQU $BEF8
TEMP9         EQU $BEF9
TEMPA         EQU $BEFA
TEMPB         EQU $BEFB
TEMPC         EQU $BEFC
TEMPD         EQU $BEFD
TEMPE         EQU $BEFE
TEMPF         EQU $BEFF

;other variables

TIME          EQU $BF00
OLDSTACK      EQU $BF04
UDGPTR        EQU $BF06
FONTPTR       EQU $BF08
TMPSTACK      EQU $BF7E
