  SETDP $BE

;sys vars
TEMP0       EQU $BE00
TEMP1       EQU $BE01
TEMP2       EQU $BE02
TEMP3       EQU $BE03
TEMP4       EQU $BE04
TEMP5       EQU $BE05
TEMP6       EQU $BE06
TEMP7       EQU $BE07
ERR_BEEP    EQU $BE08
KEY_BEEP    EQU $BE09
UNUSED1     EQU $BE0A
UNUSED2     EQU $BE0B
RAMTOP      EQU $BE0C
UDG         EQU $BE0E

TIME        EQU $BF72  
IRQPTR      EQU $BF76
FIRQPTR     EQU $BF78
SWIPTR      EQU $BF7A
SWI2PTR     EQU $BF7C
SWI3PTR     EQU $BF7E
 
